### ISSUE TITLE
Recreate Experiments

### ISSUE THREAD

**Issue by raphaelschwinger** [DBD-research-group/E2E-AudioClassfication#1]
In order to use EAT on our bird data, we first need to recreate their experiments. The learned models can then solve as pretrained models for bird detection.

## Tasks

- [x] run code in container
- [x] acquire ESC-50 dataset
- [x] train EAT-S on ESC-50 dataset -> overfitting in first test, need to understand thier code
- [x] use Lightning API to get order in the code and understand it
	- [x] lightning Basics
	- [x]  understand custom dataloader
	- [x] first train run
	- [x] test
	- [x] augmentations
	- [x] complete training (multi gpu?)
	- [x] tidy up code and make PR
- [x] evaluate on ESC-50 
- [ ] AudioSet?
- [ ] UrbanSound8K?
- [ ] EAT-m?

**Comment by raphaelschwinger** [comment]
See branch `lightning` and notebook `lightning-trainer.ipynb`
